
services:
  db:
    image: postgres:17
    container_name: postgres_test_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ../sql/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ../sql/insert_data.sql:/docker-entrypoint-initdb.d/02_insert_data.sql
      - ../sql/sample_queries.sql:/docker-entrypoint-initdb.d/03_sample_queries.sql
