# Usar una imagen oficial de Maven para construir el proyecto
FROM maven:3.9.9-eclipse-temurin-21 AS builder

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo pom.xml y los archivos de origen al contenedor
COPY pom.xml .
COPY src ./src

# Construir el proyecto
RUN mvn clean package -DskipTests

# Usar una imagen oficial de Java para ejecutar el proyecto
FROM eclipse-temurin:21-jdk

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo .jar generado desde el contenedor de compilación
COPY --from=builder /app/target/*.jar app.jar

# Exponer el puerto en el que corre el backend (modificar según la configuración de Spring Boot)
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
